name: deploy to server
on:
  push:
    branches:
        - main
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH With Ec2 instance
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Making git safe directory
              run: |
                ssh -o StrictHostKeyChecking=no ubuntu@13.61.8.180 << 'EOF'
                git config --global --add safe.directory /var/www/html/CRM
                EOF
            
            - name: Deploy To Server
              run: |
               ssh -o StrictHostKeyChecking=no ubuntu@13.61.8.180 << 'EOF'
               set -e
               cd /var/www/html/CRM/
               LAST_COMMIT=$(git rev-parse HEAD)
               echo $LAST_COMMIT > /home/ubuntu/last_commit

               git checkout main
               git pull origin main || {
               echo "Deployment Fail"
               git reset --hard $(cat /home/ubuntu/last_commit);
               exit 1;
               }
               chown -R www-data:www-data /var/www/html/CRM
               EOF

            - name: Send mail
              if: success()
              uses: dawidd6/action-send-mail@v4
              with:
                 server_address: smtp.yandex.com
                 server_port: 465
                 username: faizan.ahmed@voxtrongroup.com
                 password: ogfwbxcuvmcfzave
                 subject: "Deployment Sucessful"
                 to: ${{secrets.MAIL_USERNAME}}
                 from: faizan.ahmed@voxtrongroup.com
                 body: Build job completed successfully!
            
            - name: Send mail
              if: failure()
              uses: dawidd6/action-send-mail@v4
              with:
                 server_address: smtp.yandex.com
                 server_port: 465
                 username: faizan.ahmed@voxtrongroup.com
                 password: ogfwbxcuvmcfzave
                 subject: "Deployment Sucessful"
                 to: ${{secrets.MAIL_USERNAME}}
                 from: faizan.ahmed@voxtrongroup.com
                 body: Build job completed successfully!
            

